M48
; DRILL file KiCad 10.0.4 date 2026-07-13T13:08:01
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-13T13:08:01+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.580
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.660
%
G90
G05
T2
X81.665Y-98.5
T1
X81.665Y-91.21G85X81.665Y-90.79
G05
M30
